### ISSUE TITLE
"Package unzip is not available, but is referred to by another package" on consul files install.sh

### ISSUE THREAD

**Issue by richardx14** [turnbullpublishing/tf_consul#5]
I am running through the Consul cluster creation chapter.  Terraform apply is exiting with the following error.  Any ideas on what I have done wrong please?  I am not sure what other info is relevant.  I believe the apply is getting as far as running install.sh.

_```
module.consul.aws_instance.server[0] (remote-exec): Package unzip is not available, but is referred to by another package.
module.consul.aws_instance.server[0] (remote-exec): This may mean that the package is missing, has been obsoleted, or
module.consul.aws_instance.server[0] (remote-exec): is only available from another source

module.consul.aws_instance.server[0] (remote-exec): E: Package 'unzip' has no installation candidate

Error: Error applying plan:

1 error(s) occurred:
```_

**Comment by jamtur01** [comment]
Can you use `apt-get` from that VPC/instance to update packages? That usually suggests a failure to update packages.

**Comment by richardx14** [comment]
Yep - when directly logging into that VPC/instance, the apt-get updates and unzip installs work perfectly.  

I have tried the apply a few times now, this issue has occurred each time apart from one occasion when the updates and installs worked on the first note and then failed on the second - still with the unzip package install error.

As a newbie, I am a little lost.  I have attached the screen ouput from terraform apply.  Any thoughts would be appreciated.


[terraform consul  unzip error logs.txt](https://github.com/turnbullpress/tf_consul/files/1511050/terraform.consul.unzip.error.logs.txt)

**Comment by jamtur01** [comment]
So I've tested this last night and the only way i could replicate the error was to block access to the Ubuntu updates site. Otherwise it worked perfectly on six applies. I  don't have any good answers to this I am afraid, especially if it worked at one point. :( 

Can you run a terraform destroy and start from scratch?

**Comment by richardx14** [comment]
I had tried the destroy and apply a few times.  I have some updates though.

1.  A colleague suggested cloning tf_consul and repeating the `sudo apt-get update -y` line in install.sh.  This worked first time.
2.  I then removed the additional `sudo apt-get update -y` line and added a `sleep 180` **before** the `sudo apt-get update -y` line.  This worked too.
3.  I also tried going to back your original repo but again, that hit the same error.

(I did a destroy before each of these steps).

So guessing it is some timing issue?

Either way, I am glad to be back up and running.  Thanks for quick replies and for a great book.

**Comment by jamtur01** [comment]
Okay - glad it's working!

**Comment by kojoru** [comment]
This is one of the places I found when researching a similar issue. Since I found the answer, thought I'd post it here as well for reference of people googling it.

In my case it was due to `cloud-init`. In AWS sources for `apt-get` are populated after the machine is ready, so theoretically you can connect and start running `apt-get update` before this is finished. That's also why `sleep` helps. 

The more reliable solution however is to wait for the cloud-init itself: `cloud-init status --wait`. After that command your `apt-get update` should update the sources properly and everything should be installable.
